spring:

  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/beyond_clouds?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: beyond
    password: Beyond2020#

  # 邮箱
  mail:
    host: smtp.163.com
    username: 13546386889@163.com
    password: 100centa30822
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
        imap:
          ssl:
            socketFactory:
              fallback: false

  # elasticsearch
  data:
    elasticsearch:
      repositories:
        enabled: false
  elasticsearch:
    rest:
      uris: http://localhost:9200

  # kafka
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: beyond-clouds
      enable-auto-commit: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

server:
  tomcat:
    max-swallow-size: 100MB

# swagger
swagger:
  enable: false

# 阿里云
aliyun:
  access-key-id: LTAIeHWeydaWT3ZZ
  access-key-secret: 2FTWlODpzEZjsBQw10NO6SUBMwYOcL
  oss:
    bucket: beyondclouds
    endpoint: http://oss-cn-beijing.aliyuncs.com
    base-url: https://beyondclouds.oss-cn-beijing.aliyuncs.com
  sms:
    domain: dysmsapi.aliyuncs.com
    version: 2017-05-25
    action: SendSms
    region-id: cn-hangzhou
    sign-name: 段启岩
    template-code-map: {verifyCode: SMS_142384912}

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:cn/meteor/beyondclouds/modules/**/xml/*.xml
logging:
  level:
    cn:
      meteor:
        beyondclouds: info

# 云里云外
beyondclouds:
  debug: false
  global-prevent-duplicate: true
  auth:
    qq:
      client-id: 101846021
      client-secret: 5bc41deeb7e152e2e6aff97726bbf86a
      redirect-uri: http://meteor.natapp1.cc/auth/qq
  kafka:
    topics:
      data-item-change: topic.beyondclouds.dataitem.change
      user-action: topic.beyondclouds.useraction